(()=>{
const data=[
{name:'刘阳辉',title:'副教授',tag:'神经形态器件',initial:'刘',field:'氧化物薄膜晶体管、神经形态器件、新型生物化学传感器',unit:'中山大学材料学院',email:'联系邮箱请通过中山大学官方主页获取',link:'https://materials.sysu.edu.cn/teacher/163',about:'主要从事氧化物薄膜晶体管、神经形态器件及新型生物化学传感器研究。',edu:'博士：中国科学院大学 / 宁波材料技术与工程研究所（材料物理与化学）\n学士：南昌大学（材料科学与工程）',papers:['IEEE Electron Device Letters · 2024','Nano Research · 2024','Journal of Materials Chemistry C · 2024'],hobbies:'科研交流、器件设计与技术探索'},
{name:'汪宏',title:'副教授',tag:'宽禁带半导体',initial:'汪',field:'宽禁带半导体外延生长及器件制备、有机半导体材料与器件、柔性传感器',unit:'中山大学材料学院',email:'联系邮箱请通过中山大学官方主页获取',link:'https://materials.sysu.edu.cn/teacher/152',about:'主要开展宽禁带半导体外延生长及器件制备、有机半导体材料与器件、柔性传感器研究。',edu:'博士：厦门大学（物理化学）\n联合培养：德国明斯特大学\n学士：厦门大学（化学）',papers:['宽禁带半导体相关代表性研究 · 2024','有机半导体材料与器件相关研究','柔性传感器相关研究'],hobbies:'学术交流、材料器件探索'},
{name:'曾剑敏',title:'副教授 · 博士生导师',tag:'光电忆阻与类脑芯片',initial:'曾',field:'忆阻器/SRAM存算一体神经形态器件、光电忆阻器与低维光电晶体管视觉仿生器件、神经形态算法',unit:'中山大学材料学院',email:'联系邮箱请通过中山大学官方主页获取',link:'https://materials.sysu.edu.cn/teacher/726',about:'围绕存算一体神经形态器件、视觉仿生器件与神经形态算法开展研究，推动材料—器件—芯片协同设计。',edu:'博士：合肥工业大学 / 复旦大学 / 中山大学联合培养\n学士：合肥工业大学微电子学院',papers:['Science Advances · 2025 · 11 · eads2843','Advanced Science · 2024 · 11 · 2401080','Nature Communications · 2023 · 14 · 7655','Nano Letters · 2023 · 23 · 10821'],hobbies:'科研阅读、学术交流、芯片与智能感知技术'},
];
const team=document.getElementById('team');if(!team)return;
const tiers=[['教授 / PI','PROFESSOR / PI',[]],['副教授 / 助理教授','ASSOCIATE / ASSISTANT PROFESSOR',data],['博士研究生','PHD STUDENTS',[]],['硕士研究生','MASTER STUDENTS',[]]];
const card=m=>`<article class="team-member" data-name="${m.name}"><div class="member-avatar-wrap"><div class="member-avatar"><span class="initial">${m.initial}</span></div><div class="member-tags"><span>${m.tag}</span></div></div><div class="member-info"><h3>${m.name}</h3><b>${m.title}</b><p>${m.field}</p><span class="member-more">查看个人详情 →</span></div></article>`;
team.innerHTML=`<div class="section-head"><span>03</span><p>团队成员</p><h2>汇聚材料、器件与类脑芯片研究力量</h2></div><div class="team-roster">${tiers.map(t=>`<section class="team-tier"><div class="team-tier-title"><strong>${t[0]}</strong><span>${t[1]}</span></div>${t[2].length?`<div class="team-roster-grid">${t[2].map(card).join('')}</div>`:`<div class="tier-empty">成员信息持续更新中 · 欢迎优秀青年学者与研究生加入课题组</div>`}</section>`).join('')}</div><p class="note">团队成员资料以中山大学材料学院官方主页及课题组最新信息为准。</p>`;
const modal=document.createElement('div');modal.className='profile-modal';modal.id='profileModal';modal.innerHTML=`<div class="profile-shell"><aside class="profile-side"><button class="profile-close" aria-label="关闭">×</button><div class="profile-avatar"><div class="profile-avatar-inner"><span class="initial"></span></div></div><h2></h2><div class="profile-title"></div><div class="profile-meta"><span><strong>单位</strong><br>中山大学材料学院</span><span><strong>邮箱</strong><br><span class="email"></span></span><a class="official" target="_blank" rel="noopener"><strong>官方主页</strong><br>中山大学材料学院个人主页 →</a></div></aside><section class="profile-main"><span class="profile-kicker">PERSONAL PROFILE</span><h3 class="profile-name"></h3><div class="profile-tabs"><button class="profile-tab active" data-tab="about">关于我</button><button class="profile-tab" data-tab="papers">代表作</button><button class="profile-tab" data-tab="life">生活与爱好</button></div><div class="profile-pane active" data-pane="about"></div><div class="profile-pane" data-pane="papers"></div><div class="profile-pane" data-pane="life"></div></section></div>`;document.body.appendChild(modal);
const close=()=>modal.classList.remove('open');
function openProfile(name){const m=data.find(x=>x.name===name);if(!m)return;modal.querySelector('.initial').textContent=m.initial;modal.querySelector('.profile-side h2').textContent=m.name;modal.querySelector('.profile-title').textContent=m.title;modal.querySelector('.profile-name').textContent=m.name;modal.querySelector('.email').textContent=m.email;modal.querySelector('.official').href=m.link;modal.querySelector('[data-pane="about"]').innerHTML=`<h4>科研方向</h4><p>${m.about}</p><h4>教育背景</h4><p>${m.edu.replace(/\n/g,'<br>')}</p><h4>研究关键词</h4><p>${m.field}</p>`;modal.querySelector('[data-pane="papers"]').innerHTML=m.papers.map((p,i)=>`<div class="paper-item"><strong>${String(i+1).padStart(2,'0')} · ${p}</strong><span>代表性科研成果</span></div>`).join('');modal.querySelector('[data-pane="life"]').innerHTML=`<h4>兴趣与生活</h4><div class="hobby-grid"><div class="hobby-card"><strong>学术交流</strong><span>参加学术会议、组会与跨学科讨论</span></div><div class="hobby-card"><strong>技术探索</strong><span>${m.hobbies}</span></div><div class="hobby-card"><strong>团队生活</strong><span>科研之外的交流与共同成长</span></div></div><div class="photo-placeholder">生活照片轮播位 · 后续可上传照片后直接接入</div>`;modal.querySelectorAll('.profile-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab==='about'));modal.querySelectorAll('.profile-pane').forEach(p=>p.classList.toggle('active',p.dataset.pane==='about'));modal.classList.add('open');}
team.addEventListener('click',e=>{const c=e.target.closest('.team-member');if(c)openProfile(c.dataset.name)});modal.querySelector('.profile-close').onclick=close;modal.addEventListener('click',e=>{if(e.target===modal)close()});modal.addEventListener('click',e=>{const b=e.target.closest('.profile-tab');if(!b)return;modal.querySelectorAll('.profile-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');modal.querySelectorAll('.profile-pane').forEach(p=>p.classList.toggle('active',p.dataset.pane===b.dataset.tab))});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
})();
