(()=>{
const data=[
{name:'刘钢',title:'教授 · 博士生导师 · 院长助理',tag:'类脑与智能仿生',initial:'刘',field:'类脑与智能仿生器件、芯片和集成微系统',unit:'中山大学材料学院',email:'liugang82@mail.sysu.edu.cn',link:'https://materials.sysu.edu.cn/teacher/690',about:'长期从事类脑与智能仿生器件、芯片和集成微系统研究，聚焦神经形态器件、智能视觉与存算一体系统。',edu:'上海交通大学（2000—2004）\nSingapore-MIT Alliance（2004—2005）\n新加坡国立大学（2006—2009）',papers:[
{title:'Perovskite Retinomorphic Image Sensor for Embodied Intelligent Vision',journal:'Science Advances',year:'2025'},
{title:'Molecular Logic for Encrypted Massive Data Storage',journal:'Nature Communications',year:'2025'},
{title:'An ultrasmall organic Synapse for Neuromorphic Computing',journal:'Nature Communications',year:'2023'},
{title:'90% Yield Production of Polymer Nano-Memristor for In-Memory Computing',journal:'Nature Communications',year:'2021'},
{title:'Customization of 2D Atomic-Molecular Heterojuection with Manipulatible Charge-Transfer and Band Structure',journal:'Advanced Materials',year:'2024'},
{title:'Wavelength-Selective Photodetector and Neuromorphic Visual Sensor Utilizing Intrinsic Defect Semiconductor',journal:'Advanced Functional Materials',year:'2024'},
{title:'Fully-Printed Bionic Tactile E-Skin with Coupling Enhancement Effect to Recognize Object Assisted by Machine Learning',journal:'Advanced Functional Materials',year:'2023'},
{title:'A Self-Oscillated Organic Synapse for In-Memory Two-Factor Authentication',journal:'Advanced Science',year:'2024'},
{title:'Approaching the Zero-Power Operating Limit in a Self-Coordinated Organic Protonic Synapse',journal:'Advanced Science',year:'2023'},
{title:'Intepretable Surrogate Learning for Electronic Material Generation',journal:'ACS Nano',year:'2024'}],hobbies:'类脑器件、智能视觉、芯片与集成微系统'},
{name:'刘阳辉',title:'副教授',tag:'神经形态器件',initial:'刘',field:'氧化物薄膜晶体管、神经形态器件、新型生物化学传感器',unit:'中山大学材料学院',email:'liuyanghui@mail.sysu.edu.cn',link:'https://materials.sysu.edu.cn/teacher/163',about:'主要从事氧化物薄膜晶体管、神经形态器件及新型生物化学传感器研究。',edu:'博士：中国科学院大学 / 中国科学院宁波材料技术与工程研究所（材料物理与化学，2011—2016）\n学士：南昌大学（材料科学与工程，2007—2011）',papers:[
{title:'Mixed-frequency signal processing implemented by a multi-terminal electrolyte-gated transistor-based physical reservoir',journal:'IEEE Electron Device Letters',year:'2024'},
{title:'A multi-terminal ion-controlled transistor with multifunctionality and wide temporal dynamics for reservoir computing',journal:'Nano Research',year:'2024'},
{title:'A reverse Schmitt trigger with an adjustable hysteresis window implemented by mesoporous silica electrolyte-gated transistors',journal:'Journal of Materials Chemistry C',year:'2024'},
{title:'Low voltage electric-double-layer transistor nonenzymic erythromycin sensors based on molecularly imprinted polymers',journal:'Analytica Chimica Acta',year:'2024'},
{title:'Tunable bandgap of LuₓIn₁₋ₓO ternary alloy for solar-blind ultraviolet detection',journal:'IEEE Electron Device Letters',year:'2024'},
{title:'Solution-processed Ga₂O₃ films via thermal annealing for solar blind ultraviolet photovoltaic photodetectors with high photoresponsivity and fast response',journal:'ACS Applied Optical Materials',year:'2023'},
{title:'Low-temperature solution-processed Lu₂O₃ films for deep-UV photovoltaic detectors with high sensitivity',journal:'IEEE Electron Device Letters',year:'2022'},
{title:'Biodegradable natural pectin-based polysaccharide-gated low-voltage flexible oxide thin-film transistors for logic applications',journal:'ACS Applied Electronic Materials',year:'2022'},
{title:'An artificial thermal nociceptor based on xanthan gum-gated synaptic transistors to emulate human thermal nociception',journal:'Advanced Intelligent Systems',year:'2022'},
{title:'Xanthan gum-gated flexible thin-film transistor for realizing inverter functions',journal:'Thin Solid Films',year:'2022'},
{title:'Effect of annealing temperature on solar-blind ultraviolet photodetectors based on solution-processed scandium oxide films',journal:'IEEE Electron Device Letters',year:'2022'},
{title:'Humidity-Resistant Solar-Blind Ultraviolet Photodetectors Based on Solution-Processed Amorphous Scandium Oxide Films',journal:'ACS Applied Electronic Materials',year:'2022'},
{title:'Linear classification function emulated by pectin-based polysaccharide-gated multiterminal neuron transistors',journal:'Advanced Functional Materials',year:'2021'},
{title:'Bandgap engineering of ZrGaO films for deep-ultraviolet detection',journal:'IEEE Electron Device Letters',year:'2021'},
{title:'Bienenstock–Cooper–Munro learning rule realized in polysaccharide-gated synaptic transistors with tunable threshold',journal:'ACS Applied Materials & Interfaces',year:'2020'},
{title:'Freestanding artificial synapses based on laterally proton-coupled transistors on chitosan membranes',journal:'Advanced Materials',year:'2015'}],hobbies:'科研交流、器件设计与技术探索'},
{name:'汪宏',title:'副教授',tag:'宽禁带半导体',initial:'汪',field:'宽禁带半导体外延生长及器件制备、有机半导体材料与器件、柔性传感器',unit:'中山大学材料学院',email:'wanghong3@mail.sysu.edu.cn',link:'https://materials.sysu.edu.cn/teacher/152',about:'主要从事宽禁带半导体外延生长及器件制备、有机半导体材料与器件、柔性传感器等方面研究。',edu:'博士：厦门大学（物理化学，2009—2014）\n联合培养：德国明斯特大学（物理，2010—2012）\n学士：厦门大学（化学，2005—2009）',papers:[
{title:'Step-edge-induced patterning and orientation control of crystalline organic semiconductor films',journal:'Advanced Materials Interfaces',year:'2023'},
{title:'Sol–gel preparation of Sn doped gallium oxide films for application in solar-blind ultraviolet photodetectors',journal:'Journal of Materials Science',year:'2022'},
{title:'An Artificial Thermal Nociceptor Based on Xanthan Gum-Gated Synaptic Transistors to Emulate Human Thermal Nociception',journal:'Advanced Intelligent Systems',year:'2022'},
{title:'Ultrahigh Resolution Photodetector Arrays of Organic Single Microcrystals Self-Aligned on Prepatterned Electrodes',journal:'Advanced Materials Technologies',year:'2022'},
{title:'In situ observation of organic single micro-crystal fabrication by solvent vapor annealing',journal:'Journal of Materials Chemistry C',year:'2021'},
{title:'Lithographical Fabrication of Organic Single-Crystal Arrays by Area-Selective Growth and Solvent Vapor Annealing',journal:'ACS Applied Materials & Interfaces',year:'2020'},
{title:'Positioning growth of NPB crystalline nanowires on PTCDA nano-crystal template',journal:'Nanoscale',year:'2018'},
{title:'Tunable control efficiency of patterned nucleation by post-annealing',journal:'Journal of Materials Chemistry C',year:'2017'},
{title:'Area confined position control of molecular aggregates',journal:'New Journal of Physics',year:'2016'},
{title:'Tunable Organic Hetero-Patterns Via Molecule Diffusion Control',journal:'Small',year:'2014'},
{title:'Surface Microfluidic Patterning and Transporting Organic Small Molecules',journal:'Small',year:'2014'}],hobbies:'学术交流、材料器件探索'},
{name:'曾剑敏',title:'副教授 · 博士生导师',tag:'光电忆阻与类脑芯片',initial:'曾',field:'忆阻器/SRAM存算一体神经形态器件、光电忆阻器与低维光电晶体管视觉仿生器件、神经形态算法',unit:'中山大学材料学院',email:'个人主页未公开邮箱',link:'https://materials.sysu.edu.cn/teacher/726',about:'围绕存算一体神经形态器件、视觉仿生器件与神经形态算法开展研究，推动材料—器件—芯片协同设计。',edu:'博士：合肥工业大学微电子学院（2014—2021）\n博士联培：复旦大学专用集成电路与系统国家重点实验室；中山大学电子与信息工程学院\n学士：合肥工业大学微电子学院（2010—2014）',papers:[
{title:'Science Advances 2025, 11, eads2843',journal:'Science Advances',year:'2025'},
{title:'Advanced Science 2024, 11, 2401080',journal:'Advanced Science',year:'2024'},
{title:'ACS Applied Materials & Interfaces 2024, 19, 23501',journal:'ACS Applied Materials & Interfaces',year:'2024'},
{title:'Frontiers of Physics 2024, 19, 23501',journal:'Frontiers of Physics',year:'2024'},
{title:'Nature Communications 2023, 14, 7655',journal:'Nature Communications',year:'2023'},
{title:'Nano Letters 2023, 23, 10821',journal:'Nano Letters',year:'2023'},
{title:'Nanomaterials 2023, 13, 803',journal:'Nanomaterials',year:'2023'},
{title:'Nature Communications 2021, 12, 1984',journal:'Nature Communications',year:'2021'}],hobbies:'科研阅读、学术交流、芯片与智能感知技术'}
];
const team=document.getElementById('team');if(!team)return;
const tiers=[['教授 / PI','PROFESSOR / PI',data.filter(m=>m.name==='刘钢')],['副教授 / 助理教授','ASSOCIATE / ASSISTANT PROFESSOR',data.filter(m=>['刘阳辉','汪宏','曾剑敏'].includes(m.name))],['博士生','PHD STUDENTS',[]],['硕士生','MASTER STUDENTS',[]],['研究生','GRADUATE STUDENTS',[]]];
const card=m=>`<article class="team-member" data-name="${m.name}" tabindex="0"><div class="member-avatar-wrap"><div class="member-avatar"><span class="initial">${m.initial}</span></div><div class="member-tags"><span>${m.tag}</span></div></div><div class="member-info"><h3>${m.name}</h3><b>${m.title}</b><p>${m.field}</p><span class="member-more">查看个人详情 →</span></div></article>`;
const empty=()=>`<div class="tier-empty">成员信息持续更新中</div>`;
team.innerHTML=`<div class="team-page"><div class="team-title"><span>TEAM</span><h2>团队成员</h2><i></i></div><div class="team-roster">${tiers.map(t=>`<section class="team-tier"><h3 class="team-tier-title">${t[0]}</h3><div class="team-tier-en">${t[1]}</div>${t[2].length?`<div class="team-roster-grid">${t[2].map(card).join('')}</div>`:empty()}</section>`).join('')}</div></div>`;
const modal=document.createElement('div');modal.className='profile-modal';modal.id='profileModal';modal.innerHTML=`<div class="profile-shell"><aside class="profile-side"><button class="profile-close" aria-label="关闭">×</button><div class="profile-avatar"><div class="profile-avatar-inner"><span class="initial"></span></div></div><h2></h2><div class="profile-title"></div><div class="profile-meta"><span><strong>单位</strong><br>中山大学材料学院</span><span><strong>邮箱</strong><br><span class="email"></span></span><a class="official" target="_blank" rel="noopener"><strong>官方主页</strong><br>中山大学材料学院个人主页 →</a></div></aside><section class="profile-main"><span class="profile-kicker">PERSONAL PROFILE</span><h3 class="profile-name"></h3><div class="profile-tabs"><button class="profile-tab active" data-tab="about">关于我</button><button class="profile-tab" data-tab="papers">代表作</button><button class="profile-tab" data-tab="life">生活与爱好</button></div><div class="profile-pane active" data-pane="about"></div><div class="profile-pane" data-pane="papers"></div><div class="profile-pane" data-pane="life"></div></section></div>`;document.body.appendChild(modal);
const close=()=>modal.classList.remove('open');
function openProfile(name){const m=data.find(x=>x.name===name);if(!m)return;modal.querySelector('.initial').textContent=m.initial;modal.querySelector('.profile-side h2').textContent=m.name;modal.querySelector('.profile-title').textContent=m.title;modal.querySelector('.profile-name').textContent=m.name;modal.querySelector('.email').textContent=m.email;modal.querySelector('.official').href=m.link;modal.querySelector('[data-pane="about"]').innerHTML=`<h4>科研方向</h4><p>${m.about}</p><h4>教育背景</h4><p>${m.edu.replace(/\n/g,'<br>')}</p><h4>研究关键词</h4><p>${m.field}</p>`;modal.querySelector('[data-pane="papers"]').innerHTML=`<div class="paper-count">官网公开代表论文：${m.papers.length} 篇</div>`+m.papers.map((p,i)=>`<div class="paper-item"><strong>${String(i+1).padStart(2,'0')} · ${p.title}</strong><span>${p.journal} · ${p.year}</span></div>`).join('');modal.querySelector('[data-pane="life"]').innerHTML=`<h4>兴趣与生活</h4><div class="hobby-grid"><div class="hobby-card"><strong>学术交流</strong><span>参加学术会议、组会与跨学科讨论</span></div><div class="hobby-card"><strong>技术探索</strong><span>${m.hobbies}</span></div><div class="hobby-card"><strong>团队生活</strong><span>科研之外的交流与共同成长</span></div></div><div class="photo-placeholder">生活照片轮播位 · 后续可上传照片后直接接入</div>`;modal.querySelectorAll('.profile-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab==='about'));modal.querySelectorAll('.profile-pane').forEach(p=>p.classList.toggle('active',p.dataset.pane==='about'));modal.classList.add('open');}
team.addEventListener('click',e=>{const c=e.target.closest('.team-member');if(c)openProfile(c.dataset.name)});team.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.closest('.team-member')){e.preventDefault();openProfile(e.target.closest('.team-member').dataset.name)}});modal.querySelector('.profile-close').onclick=close;modal.addEventListener('click',e=>{if(e.target===modal)close()});modal.addEventListener('click',e=>{const b=e.target.closest('.profile-tab');if(!b)return;modal.querySelectorAll('.profile-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');modal.querySelectorAll('.profile-pane').forEach(p=>p.classList.toggle('active',p.dataset.pane===b.dataset.tab))});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
})();
